# Generated by Django 5.0 on 2023-12-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adoptantes',
            name='DNI',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='adoptantes',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adoptantes',
            name='userName',
            field=models.CharField(max_length=100),
        ),
    ]
