# Generated by Django 5.0 on 2023-12-15 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adoptantes_dni_alter_adoptantes_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adoptantes',
            options={'ordering': ['lastName', 'name'], 'verbose_name': 'adoptante', 'verbose_name_plural': 'adoptantes'},
        ),
        migrations.AlterModelTable(
            name='adoptantes',
            table='adoptantes',
        ),
    ]
